### PR TITLE
Some QOL updates

### PR DESCRIPTION
**Pull request by dawaltconley**
Thank you for this library! I made some changes in a branch for my own convenience, if you'd like to incorporate any:

## Non-breaking changes

- adds `$start` and `$end` arguments to the functions to allow arbitrary and non-relative positioning of the gradients within their elements.
- adds a `_gradients.scss` manifest file at the top level, for easier including.
- excludes all files except the manifest and source file from npm installs.

## Breaking changes

- moved sass functions to the module system.
- shortened the function names, to import via `@use` with their own namespace.
- added strict argument validation to the gradient functions.
- updated the README and website to reflect the new arguments and intended ways of `@use`ing in a project.

### CODE REVIEW

**Comment by oti** [comment]
@dawaltconley Thank you for your great contribution! I want to merge this PR and publish it as v3.

Also, I would like to change the build tool of index.html from gulp to npm run-script etc.

Please wait for their development.

**Comment by oti** [comment]
@dawaltconley [v3 released!](https://github.com/oti/smooth-gradient-sass-function/releases/tag/v3.0.0) thank you very much!

**Comment by oti** [comment]
@dawaltconley I stupidly forgot to npm publish v3 :bow: So I have npm published the updated v3.1 the other day.
https://www.npmjs.com/package/smooth-gradient-sass-function

**Comment by dawaltconley** [comment]
Haha, all good, glad it got published!

Btw I came across an old branch of mine when looking at this again. I was trying to clean up the API and allow for creating a gradient between any two colors:

```scss
$example: gradient.scrim($from: [$startColor, $startPosition], $to: [$endColor, $endPosition]);
```

```scss
.box {
  // 1st arg is a list, containing start color code and position (default: #000000 0)
  background-image: linear-gradient(
    to bottom,
    gradients.scrim($from: #ff0000 20%)
  );
}
```

```scss
.box {
  // 2nd arg is a list, containing end color code and position (default: transparent 100%)
  background-image: linear-gradient(
    to bottom,
    gradients.scrim($from: #ffff00 20%, $to: rgba(#ffff00, 0.2) 60%)
  );
}
```

```scss
.box {
  // args are determined by type, and can be mixed
  // this is equivalent to $from: #ffff00 0, $to: rgba(255, 255, 0, 0) 50%
  background-image: linear-gradient(
    to bottom,
    gradients.scrim($from: #ffff00, $to: 50%)
  );
}
```

I was trying to make it non-breaking by retaining support for `$opacity` (checking if the second positional argument is a unitless number) but that was a bit complicated & not sure if that makes sense, since you can also just pass a semi-transparent color to the first argument.

I can take another look at that branch when I have a chance if you're interested in any of those changes.

**Comment by oti** [comment]
@dawaltconley I think the ability to create a gradation with any two colors is wonderful! If possible, I would like to get a PR and release it as v3.2.

**Pull request merged**
